# steps:
#   - command: "cd packer/test && packer build test.json"
#   - wait

steps:
  - command: "echo $PACKER_SECURITY_GROUP"
  - wait
  - command: "packer build test.json"
    plugins:
      thedyrt/change-directory#v0.1.1:
        cd: ./packer/test