# steps:
#   - command: "cd packer/test && packer build test.json"
#   - wait

steps:
  - command: "packer build test.json"
    plugins:
      thedyrt/change-directory#v0.1.1:
        cd: ./builder-ami