# steps:
#   - command: "cd packer/test && packer build test.json"
#   - wait

steps:
  - command: "buildkite/scripts/packer-build.sh"
    plugins:
      thedyrt/change-directory#v0.1.1:
        cd: ./packer/test